### ISSUE TITLE
TypeError: 'dict' object is not callable

### ISSUE THREAD

**Issue by wandonye** [rikenmehta03/flask-to-do#2]
Got the following err:
```
data = request.json()
TypeError: 'dict' object is not callable
```
I guess it should be `data = request.json`?

**Comment by rikenmehta03** [comment]
Fixed that. It should have been 
`data = request.get_json()`

**Comment by HarryCaveMan** [comment]
yeah so I am getting the exact same error but using `request.get_json()`
